### ISSUE TITLE
Modularise and improve testing component for images

### ISSUE THREAD

**Issue by MarcelTorne** [epfml/DeAI#51]
- Make a general modularised component for testing the model

**Comment by PaulMansat** [comment]
- Need to uniformize the uploading process between images and CSV files. 
- I think we can create: 
(1) a File Upload Manager that has all the functions required to update an internal file list, 
(2) a SingleFileFrame vuejs component (with only one uploading box), 
(3) a FileUploadFrame vuejs component. 
The two vuejs components take as input a File Manager. The FileUploadFrame would take an additional prop. that defines how many uploading boxes should be created (for each label). 
This architecture allows us to have the same uploading process between images and CSV files. We can also add a parameter data_type to the File Manager so that we only keep files that are either images or CSV files. 
- The File Manager needs to be able to handle multiple files upload depending on the labels. Meaning, for documents stored in the file list, we might need to associate its label. 
I can take care of doing this, but if you have further ideas, please tell me. 
Overall this improvement makes it easier to modularise the testing component (only need to call the model stored in memory and a File Upload Manager and a result display frame)
